# Application
spring.application.name=Library Management System

# Server
server.port=8080

# SQLite Database Configuration - Compatible avec DB Browser
spring.datasource.url=jdbc:sqlite:./data/library.db?journal_mode=WAL&synchronous=NORMAL
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

# H2 Console (connectee a SQLite)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate pour SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.org.hibernate.SQL=INFO

# Disable DevTools restart
spring.devtools.restart.enabled=false
